name: .at3dcv
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - meshplot
  - numpy
  - python==3.10
  - scikit-learn
  - tqdm
  - trimesh
  - pip:
    - potpourri3d
    - robust-laplacian
