name: .at3dcv-double-model
channels:
  - anaconda
  - conda-forge
  - open3d-admin
dependencies:
  - python=3.8
  - addict
  - open3d
  - pandas
  - pip
  - plyfile
  - pyyaml
  - scikit-learn
  - tqdm
  - pip:
    - h5py
    - torch
